### ISSUE TITLE
Add log-fold-changes to res output table

### ISSUE THREAD

**Issue by jeremymsimon** [SimoneTiberi/distinct#2]
I don't currently see this as an option, but it would be nice to be able to separate the results table into up- and down-regulated genes. Currently it seems I would need to compute my own LFCs. Can you add this calculation and include it in the output table?

**Comment by SimoneTiberi** [comment]
Hi Jeremy,
Thanks for the suggestion.

The idea of `distinct` is that, instead of targeting changes in the mean, it compares entire distributions (via cdfs).
So I thought that splitting results according to lfcs, might underrate significant results with little difference in the lfc.

However, I understand that for some users it might be interesting to split results according to FCs, so I'll implement something like this in future releases.

Thanks again for the feedback,
Simone

**Comment by jeremymsimon** [comment]
Understood - whether its a true LFC or something like it, that would be very helpful! For now I will make lots of violin/density plots.

Thanks!

**Comment by SimoneTiberi** [comment]
Hi Jeremy @jeremymsimon ,
following your idea, I added a function (**log2_FC**) to compute FC, log2-FC and mean expression levels per group.

Function **top_results** (to visualize results) was also edited so that results can be sorted by FC and/or split in up- and down-regulated.

I just updated the package on Github (v 1.0.3 and v 1.1.3), but the updates will also be on Bioc within a couple days.

Let me know if you have further comments, and thanks again for your feedback.
Simone

**Comment by SimoneTiberi** [comment]
Hi @jeremymsimon Jeremy,
I realized my previous version of `log2_FC` function was incredibly slow on big datasets (and basically impossible to use): I edited it and it now much faster.

For instance, on the dataset you sent me it takes ~10 seconds on my laptop.

It's on v 1.0.4 and 1.1.4 (just uploaded on Github, and on Bioc in a couple of days).

Simone

**Comment by jeremymsimon** [comment]
Thanks @SimoneTiberi! I might recommend incorporating this function into the main `distinct_test` function. I imagine most users will want their primary output table to contain this information by default, but of course it's up to you!

**Comment by SimoneTiberi** [comment]
Thanks for the input Jeremy.
I thought about it, but since `distinct_test` requires significant computational time, I preferred to leave the two functions separates (so differential tests doesn't have run again in case log2_FC crashes).

Furthermore, keeping them separate, allows rapid re-calculation of FCs and log2-FC based on different inputs (cpms, log-cpms, vst-residuals, etc...).

Btw, many thanks for your comments in these past weeks: your feedback really helped me improve `distinct`'s usability.

**Comment by jeremymsimon** [comment]
No problem- sounds good!

Just a side note for you and others who may end up here: the way that `Seurat` and `SingleCellExperiment` interface is rather confusing. It took me a while to make sure I knew which values (raw, or normalized/`scTransform`ed) were being exported out of my Seurat object. I think this is because `scTransform` values don't populate the same data slot as `NormalizeData` does (ie I think it populates `scale.data` but not `data`), and therefore the `counts` and `logcounts` slots of my SCE object were identical. This is not your issue to solve, but I do wonder if it would streamline/clarify things a bit if `distinct` could take Seurat objects directly as input, that way the user can be explicit about the assay/slot they use. Or if not, it might be good if you (or we, if you'd prefer) whip up a vignette to make this clear for Seurat users. It's likely straightforward for those following the standard `NormalizeData` workflow in Seurat, but `scTransform` users might _think_ they're using normalized data when actually they're using raw counts.

**Comment by SimoneTiberi** [comment]
True, I didn't think about this issue.

`distinct` currently inputs a `SummarizedExperiment ` or a `SingleCellExperiment`.

Converting a Seurat object into a `SingleCellExperiment` seems straightforward (https://satijalab.org/seurat/v3.2/conversion_vignette.html), even though I haven't tried myself.

For `scTransform`, you can store the normalized counts as an assay of your SingleCellExperiment `x`; when calling `distinct_test` you then have to specify the name of the assay to use (in this case `vstresiduals`):
```
assays(x)$vstresiduals = sctransform::vst( assays(x)$counts )$y

res = distinct_test(x, name_assays_expression = "vstresiduals", ...)
```

Do you think it's unclear?
I might add a few rows to the vignette to mention these issues.

**Comment by jeremymsimon** [comment]
Yeah I'm not very familiar with using either `SummarizedExperiment` or `SingleCellExperiment` so this was all pretty new to me. Annotating like you did here makes logical sense, now that I see it, but I would need to verify that the values that come out of `sctransform::vst( assays(x)$counts )$y` are the same as the ones in the `SCT` slot...though I assume so? But yes, without doing what you show here, `scTransform` users would see by default that their object has `counts` and `logcounts` and might assume the latter to be `scTransform` counts, but that is not the case. So some additional info in your vignette on this would be helpful!

**Comment by SimoneTiberi** [comment]
Right, I'll add a few lines in the vignettes to clarify these two aspects.

Thanks again for your comments.
