### ISSUE TITLE
object '.doSnowGlobals' not found

### ISSUE THREAD

**Issue by jeremymsimon** [SimoneTiberi/distinct#4]
I can run `distinct_test()` on one core with no issue, but if I specify `n_cores=4` I get an error: 
```
object '.doSnowGlobals' not found`
```

To test, I re-installed `doParallel` to my typical custom Rlibs directory, which also appears at the top of my `.libPaths()`: 

```
.libPaths()
[1] "/proj/jmsimon/Rlibs40_new"            
[2] "/proj/jmsimon/R-4.0.2/lib64/R/library"
```

but the error persisted.

[This thread](https://stackoverflow.com/questions/25079527/error-object-dosnowglobals-not-found) suggests there's an issue with worker threads not having access to `doParallels` but if it's at the top of my `.libPaths()` I'm not sure what else I can do to ensure that.

**Comment by SimoneTiberi** [comment]
Hi Jeremy,
Many thanks for creating an issue.

As we discussed, it'd be a general issue with `doParallel`, not specific to `distinct`
But I am still not sure what exactly is causing this...I'm investigating.

Does it also happen with the example dataset and on other machines (e.g., OS vs Unix)?

Some users discuss about the same issue with `Seurat`: https://github.com/satijalab/seurat/issues/603#issuecomment-405396802
This trick worked for 1 user:
`I cleared out my entire personal R library, did a clean install of Seurat and all its dependencies, and forced .libpaths() to my own library dir. That did the trick. Make sure you have snow, doSNOW, doParallel, Matrix packages fully installed/updated/accessible.`

EDIT: Can you try to simply install packages snow and doSNOW and see if the error persists?

Otherwise, could you try what the user suggests above?
Although, it might take a while to install all dependencies again.

Thanks,
Simone

**Comment by jeremymsimon** [comment]
Thanks Simone, I solved it. I'll try to describe fully here in case other users end up in the same situation

At the start of my R session, I had been manually adding my custom library directory to my `.libPaths()` with

```
.libPaths("/proj/jmsimon/Rlibs40")
```

This would push that custom directory to the top such that it became the default install and load location for all libraries. I wrongly assumed that this would work for all packages and processes.

The problem seems to be that parallel processes do not also load that same custom directory, they only see the default library path associated with my R build as though no changes to my `.libPaths()` were ever made. If I install `distinct` and all of these dependencies (`doParallel`, `snow`, `doSNOW`, etc) there and un-set my custom libPath directory such that ONLY the default path was listed, `distinct_test()` with multiple cores finishes without error. 

Note it may be possible to set `LD_LIBRARY_PATHS` or similar to use my custom library directory and similarly get around this error, but I have not tested it.

**Comment by SimoneTiberi** [comment]
Oh great, many thanks for solving this and posting the solution here!

**Comment by ruqianl** [comment]
Just would like to add that setting the environment variable R_LIBS_USER can fix this issue. 
```
Sys.setenv("R_LIBS_USER"="/mnt/XXX/XXX/Rlibs/4.1.2/")
```
